data:
  dataset_train: /home/karen/data_science_project/data/row/train54.csv
  dataset_eval: /home/karen/data_science_project/data/row/eval.csv
  target_column: sale_amount
  datetime_column: dt
  fracture: 0.1

preprocessing:
  # Feature engineering configuration
  lag_periods: [1, 2, 3, 7, 14, 21]  # Hours to lag
  rolling_windows: [6, 24, 168]      # 6h, 1day, 1week
  seasonal_periods: [24, 168]        # Daily and weekly patterns
  outlier_threshold: 3.0             # Z-score threshold

models:
  baseline:
    linear:
      fit_intercept: true
    ridge:
      alpha: 10.0
      fit_intercept: true
    lasso:
      alpha: 0.01
      fit_intercept: true
    random_forest:
      n_estimators: 300
      max_depth: 20
    gradient_boosting:
      n_estimators: 200
      learning_rate: 0.1
      max_depth: 5


  advanced:
    lstm:
      hidden_size: 64
      num_layers: 2
      dropout: 0.2
      sequence_length: 168  # 1 week
training:
  test_size: 0.2
  validation_size: 0.1
  cv_folds: 5
  random_state: 42

evaluation:
  metrics: [mae, rmse, mape, bias]
  forecast_horizons: [1, 6, 24, 168]  # 1h, 6h, 1day, 1week
